language: generic
os: linux
dist: xenial

services:
  - docker

before_install:
  - docker build -t vtomenko/fibo-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vtomenko/fibo-client npm run test

after_success:
  - docker build -t vtomenko/fibo-client ./client
  - docker build -t vtomenko/fibo-nginx ./nginx
  - docker build -t vtomenko/fibo-server ./server
  - docker build -t vtomenko/fibo-worker ./worker
  - echo "$DOCKER_HUB_PASSWORD" | docker login docker.io -u $DOCKER_HUB_USERNAME --password-stdin
  - docker push vtomenko/fibo-client
  - docker push vtomenko/fibo-nginx
  - docker push vtomenko/fibo-server
  - docker push vtomenko/fibo-worker


deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "fib"
  env: "Fib-env"
  bucket: "elasticbeanstalk-us-east-1-004891899541"
  bucket_path: "fib"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_ACCESS_SECRET


